import { TicketListing } from './types';

export const MOCK_TICKETS: TicketListing[] = [
  {
    id: '1',
    section: '123',
    row: '2',
    quantity: 2,
    pricePerTicket: 6400,
    feesPerTicket: 985,
    rating: 10,
    ratingLabel: 'Amazing',
    isBestDeal: true,
  },
  {
    id: '2',
    section: '123',
    row: '3',
    quantity: 2,
    pricePerTicket: 7480,
    feesPerTicket: 1020,
    rating: 10,
    ratingLabel: 'Amazing',
  },
  {
    id: '3',
    section: '325',
    row: '12',
    quantity: 4,
    pricePerTicket: 6050,
    feesPerTicket: 840,
    rating: 9,
    ratingLabel: 'Great',
  },
  {
    id: '4',
    section: '110',
    row: '5',
    quantity: 2,
    pricePerTicket: 12000,
    feesPerTicket: 1985,
    rating: 8,
    ratingLabel: 'Good',
  },
  {
    id: '5',
    section: '215',
    row: '8',
    quantity: 2,
    pricePerTicket: 8820,
    feesPerTicket: 1100,
    rating: 9,
    ratingLabel: 'Great',
  },
  {
    id: '6',
    section: '101',
    row: '1',
    quantity: 2,
    pricePerTicket: 18500,
    feesPerTicket: 2500,
    rating: 8,
    ratingLabel: 'Premium',
  },
  {
    id: '7',
    section: '340',
    row: '20',
    quantity: 6,
    pricePerTicket: 6200,
    feesPerTicket: 750,
    rating: 7,
    ratingLabel: 'Value',
  },
  {
    id: '8',
    section: '205',
    row: '15',
    quantity: 2,
    pricePerTicket: 9400,
    feesPerTicket: 1200,
    rating: 9,
    ratingLabel: 'Great',
  },
  {
    id: '9',
    section: '126',
    row: '4',
    quantity: 2,
    pricePerTicket: 15150,
    feesPerTicket: 2100,
    rating: 10,
    ratingLabel: 'Amazing',
  },
  {
    id: '10',
    section: '315',
    row: '10',
    quantity: 2,
    pricePerTicket: 6750,
    feesPerTicket: 850,
    rating: 8,
    ratingLabel: 'Good',
  },
];

export const WHATSAPP_NUMBER = '19315054197';
export const WHATSAPP_MESSAGE = 'Hey, I want to get a ticket';
